# Generated by Django 4.0.2 on 2022-02-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_post_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Картинка',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
