# Generated by Django 4.0.2 on 2022-02-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posts_картинка'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Дата',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='Картинка',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='Текст',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='Заголовок',
            new_name='title',
        ),
    ]
