# Generated by Django 4.0.2 on 2022-02-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Заголовок События',
        ),
    ]
