# Generated by Django 4.0.2 on 2022-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_заголовок события'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Изображение События',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Текст События',
            new_name='Text',
        ),
        migrations.AddField(
            model_name='event',
            name='Title',
            field=models.CharField(default='Заголовок', max_length=300),
        ),
    ]
